### PR TITLE
Parallel processing

### PR DESCRIPTION
**Pull request by myint**
I wanted to speed things up, so I added a `--jobs` option.

By default, this changes nothing. But if you use `--jobs`, it enables the builds to be run in that many parallel jobs. If `--jobs` is set to zero, the number of parallel jobs is chosen automatically based on number of CPU cores.

### CODE REVIEW

**Comment by myint** [comment]
Here is a benchmark, run on one of my projects (docformatter).

With 4 parallel jobs:

``` bash
$ time travis-solo -j4
...
python2.6: Build succeeded
python2.7: Build succeeded
pypy: Build succeeded
python3.2: Build succeeded
python3.3: Build succeeded

real    0m28.669s
user    0m52.849s
sys 0m10.127s
```

The default (without parallel processing):

``` bash
$ time travis-solo
...
python2.6: Build succeeded
python2.7: Build succeeded
pypy: Build succeeded
python3.2: Build succeeded
python3.3: Build succeeded

real    1m28.445s
user    1m7.214s
sys 0m12.633s
```

**Comment by jstasiak** [comment]
Hi, thanks a lot for the contribution. I'll take a closer look at the patch when I have a moment, looks all right!

**Comment by jstasiak** [comment]
Ok this looks really cool. There one issue though - multiple jobs using the same Python interpreter (one with environmental variable `SWITCH=x`, another with `SWITCH=y` etc.) - having them run at the same time will cause errors (updating currently running Python interpreter, trying to build the package when some other process is already doing that etc.)

So in order to merge this patch we probably need a protection against running multiple jobs using single virtualenv/Python concurrently.

**Comment by myint** [comment]
I see. It looks like the problem is that travis-solo is relying on side effects to set the environment variables. (It sets the environment variables of the parent process.) The problem can be fixed by, instead, explicitly passing the environment variables to the subprocesses via the [`env`](http://docs.python.org/3/library/subprocess.html) parameter.

I'll take a look at this later this week.

**Comment by myint** [comment]
Okay, see my latest commit.

**Comment by myint** [comment]
Actually, there is a bit more work to do. The issue I solved is necessary, but wasn't what you were referring to. I'll have to take a look at that later.

**Comment by myint** [comment]
Shouldn't each environment setting get its own virtualenv (to match Travis CI more closely)? For example, if there was `SWITCH=x` and `SWITCH=y`, instead of

```
.travis-solo/2.7
.travis-solo/3.3
```

it seems like it would be better to have

```
.travis-solo/2.7-SWITCH=x
.travis-solo/2.7-SWITCH=y
.travis-solo/3.3-SWITCH=x
.travis-solo/3.3-SWITCH=y
```

The current behavior, of reusing the same virtualenv, seems like it could cause problems (even without multithreading). For example, if the environment variable is used to switch between different `pip` install commands, there could be problems.

``` yaml
env:
    - SWITCH=x
    - SWITCH=y
script:
    - if [ "$SWITCH" == "x" ]; then pip install foo; else pip install bar; fi
```

**Comment by jstasiak** [comment]
Thanks for the patches. Yeah, each environment should have it's own virtualenv ideally. This seems like a oneliner though, I'll push something that makes it right.

**Pull request merged**
